name: Get Arxiv Papers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.6.10

      - name: install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      - name: run script
        run: |
          git pull
          python rss_daily.py
      
      - name: push markdown file
        run: |
          git config user.name wwd29
          git config user.email tj.29@qq.com
          git add .
          git commit -m "update"
          git push --force origin main
